server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://server-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third-party
          uri: lb://server-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

  ## 前端项目，/api
  ## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
  ## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree
