server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://server-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://server-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third-party
          uri: lb://server-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://server-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://server-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://server-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


        - id: gmall_host_route
          uri: lb://server-product
          predicates:
            - Host=gmall.cn,gmall.com,item.gmall.com

        - id: gmall_search_route
          uri: lb://server-search
          predicates:
            - Host=search.gmall.com

        - id: gmall_auth_route
          uri: lb://gmall-auth-server
          predicates:
            - Host=auth.gmall.com

        - id: gmall_cart_route
          uri: lb://gmall-cart
          predicates:
            - Host=cart.gmall.com

        - id: gmall_order_route
          uri: lb://gmall-order
          predicates:
            - Host=order.gmall.com

        - id: gmall_member_route
          uri: lb://gmall-member
          predicates:
            - Host=member.gmall.com

        - id: gmall_seckill_route
          uri: lb://server-seckill
          predicates:
            - Host=seckill.gmall.com

  ## 前端项目，/api
  ## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
  ## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree
