server:
  port: 11000

spring:
  application:
    name: server-ware
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.33.10:3306/mall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  #  mapper-locations: classpath*:/mapper/**/*.xml # 扫描所有包
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

# 打印sql
logging:
  level:
    com.ylkget.gmall: debug